/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "frame.piqi.pb-c.h"
void   frame__init
                     (Frame         *message)
{
  static Frame init_value = FRAME__INIT;
  *message = init_value;
}
size_t frame__get_packed_size
                     (const Frame *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t frame__pack
                     (const Frame *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t frame__pack_to_buffer
                     (const Frame *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Frame *
       frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Frame *)
     protobuf_c_message_unpack (&frame__descriptor,
                                allocator, len, data);
}
void   frame__free_unpacked
                     (Frame *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   operand_value_list__init
                     (OperandValueList         *message)
{
  static OperandValueList init_value = OPERAND_VALUE_LIST__INIT;
  *message = init_value;
}
size_t operand_value_list__get_packed_size
                     (const OperandValueList *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_value_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t operand_value_list__pack
                     (const OperandValueList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_value_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t operand_value_list__pack_to_buffer
                     (const OperandValueList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_value_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OperandValueList *
       operand_value_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OperandValueList *)
     protobuf_c_message_unpack (&operand_value_list__descriptor,
                                allocator, len, data);
}
void   operand_value_list__free_unpacked
                     (OperandValueList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_value_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   operand_info__init
                     (OperandInfo         *message)
{
  static OperandInfo init_value = OPERAND_INFO__INIT;
  *message = init_value;
}
size_t operand_info__get_packed_size
                     (const OperandInfo *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t operand_info__pack
                     (const OperandInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t operand_info__pack_to_buffer
                     (const OperandInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OperandInfo *
       operand_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OperandInfo *)
     protobuf_c_message_unpack (&operand_info__descriptor,
                                allocator, len, data);
}
void   operand_info__free_unpacked
                     (OperandInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   operand_info_specific__init
                     (OperandInfoSpecific         *message)
{
  static OperandInfoSpecific init_value = OPERAND_INFO_SPECIFIC__INIT;
  *message = init_value;
}
size_t operand_info_specific__get_packed_size
                     (const OperandInfoSpecific *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info_specific__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t operand_info_specific__pack
                     (const OperandInfoSpecific *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info_specific__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t operand_info_specific__pack_to_buffer
                     (const OperandInfoSpecific *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info_specific__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OperandInfoSpecific *
       operand_info_specific__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OperandInfoSpecific *)
     protobuf_c_message_unpack (&operand_info_specific__descriptor,
                                allocator, len, data);
}
void   operand_info_specific__free_unpacked
                     (OperandInfoSpecific *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_info_specific__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reg_operand__init
                     (RegOperand         *message)
{
  static RegOperand init_value = REG_OPERAND__INIT;
  *message = init_value;
}
size_t reg_operand__get_packed_size
                     (const RegOperand *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &reg_operand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reg_operand__pack
                     (const RegOperand *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &reg_operand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reg_operand__pack_to_buffer
                     (const RegOperand *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &reg_operand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RegOperand *
       reg_operand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RegOperand *)
     protobuf_c_message_unpack (&reg_operand__descriptor,
                                allocator, len, data);
}
void   reg_operand__free_unpacked
                     (RegOperand *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &reg_operand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mem_operand__init
                     (MemOperand         *message)
{
  static MemOperand init_value = MEM_OPERAND__INIT;
  *message = init_value;
}
size_t mem_operand__get_packed_size
                     (const MemOperand *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &mem_operand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mem_operand__pack
                     (const MemOperand *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &mem_operand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mem_operand__pack_to_buffer
                     (const MemOperand *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &mem_operand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MemOperand *
       mem_operand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MemOperand *)
     protobuf_c_message_unpack (&mem_operand__descriptor,
                                allocator, len, data);
}
void   mem_operand__free_unpacked
                     (MemOperand *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &mem_operand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   operand_usage__init
                     (OperandUsage         *message)
{
  static OperandUsage init_value = OPERAND_USAGE__INIT;
  *message = init_value;
}
size_t operand_usage__get_packed_size
                     (const OperandUsage *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_usage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t operand_usage__pack
                     (const OperandUsage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_usage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t operand_usage__pack_to_buffer
                     (const OperandUsage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_usage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OperandUsage *
       operand_usage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OperandUsage *)
     protobuf_c_message_unpack (&operand_usage__descriptor,
                                allocator, len, data);
}
void   operand_usage__free_unpacked
                     (OperandUsage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &operand_usage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   taint_info__init
                     (TaintInfo         *message)
{
  static TaintInfo init_value = TAINT_INFO__INIT;
  *message = init_value;
}
size_t taint_info__get_packed_size
                     (const TaintInfo *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t taint_info__pack
                     (const TaintInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t taint_info__pack_to_buffer
                     (const TaintInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaintInfo *
       taint_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaintInfo *)
     protobuf_c_message_unpack (&taint_info__descriptor,
                                allocator, len, data);
}
void   taint_info__free_unpacked
                     (TaintInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   std_frame__init
                     (StdFrame         *message)
{
  static StdFrame init_value = STD_FRAME__INIT;
  *message = init_value;
}
size_t std_frame__get_packed_size
                     (const StdFrame *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &std_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t std_frame__pack
                     (const StdFrame *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &std_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t std_frame__pack_to_buffer
                     (const StdFrame *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &std_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StdFrame *
       std_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StdFrame *)
     protobuf_c_message_unpack (&std_frame__descriptor,
                                allocator, len, data);
}
void   std_frame__free_unpacked
                     (StdFrame *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &std_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   syscall_frame__init
                     (SyscallFrame         *message)
{
  static SyscallFrame init_value = SYSCALL_FRAME__INIT;
  *message = init_value;
}
size_t syscall_frame__get_packed_size
                     (const SyscallFrame *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &syscall_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t syscall_frame__pack
                     (const SyscallFrame *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &syscall_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t syscall_frame__pack_to_buffer
                     (const SyscallFrame *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &syscall_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SyscallFrame *
       syscall_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SyscallFrame *)
     protobuf_c_message_unpack (&syscall_frame__descriptor,
                                allocator, len, data);
}
void   syscall_frame__free_unpacked
                     (SyscallFrame *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &syscall_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   argument_list__init
                     (ArgumentList         *message)
{
  static ArgumentList init_value = ARGUMENT_LIST__INIT;
  *message = init_value;
}
size_t argument_list__get_packed_size
                     (const ArgumentList *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &argument_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t argument_list__pack
                     (const ArgumentList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &argument_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t argument_list__pack_to_buffer
                     (const ArgumentList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &argument_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ArgumentList *
       argument_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ArgumentList *)
     protobuf_c_message_unpack (&argument_list__descriptor,
                                allocator, len, data);
}
void   argument_list__free_unpacked
                     (ArgumentList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &argument_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   exception_frame__init
                     (ExceptionFrame         *message)
{
  static ExceptionFrame init_value = EXCEPTION_FRAME__INIT;
  *message = init_value;
}
size_t exception_frame__get_packed_size
                     (const ExceptionFrame *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &exception_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t exception_frame__pack
                     (const ExceptionFrame *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &exception_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t exception_frame__pack_to_buffer
                     (const ExceptionFrame *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &exception_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExceptionFrame *
       exception_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExceptionFrame *)
     protobuf_c_message_unpack (&exception_frame__descriptor,
                                allocator, len, data);
}
void   exception_frame__free_unpacked
                     (ExceptionFrame *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &exception_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   taint_intro_frame__init
                     (TaintIntroFrame         *message)
{
  static TaintIntroFrame init_value = TAINT_INTRO_FRAME__INIT;
  *message = init_value;
}
size_t taint_intro_frame__get_packed_size
                     (const TaintIntroFrame *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t taint_intro_frame__pack
                     (const TaintIntroFrame *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t taint_intro_frame__pack_to_buffer
                     (const TaintIntroFrame *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaintIntroFrame *
       taint_intro_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaintIntroFrame *)
     protobuf_c_message_unpack (&taint_intro_frame__descriptor,
                                allocator, len, data);
}
void   taint_intro_frame__free_unpacked
                     (TaintIntroFrame *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   taint_intro_list__init
                     (TaintIntroList         *message)
{
  static TaintIntroList init_value = TAINT_INTRO_LIST__INIT;
  *message = init_value;
}
size_t taint_intro_list__get_packed_size
                     (const TaintIntroList *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t taint_intro_list__pack
                     (const TaintIntroList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t taint_intro_list__pack_to_buffer
                     (const TaintIntroList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaintIntroList *
       taint_intro_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaintIntroList *)
     protobuf_c_message_unpack (&taint_intro_list__descriptor,
                                allocator, len, data);
}
void   taint_intro_list__free_unpacked
                     (TaintIntroList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   taint_intro__init
                     (TaintIntro         *message)
{
  static TaintIntro init_value = TAINT_INTRO__INIT;
  *message = init_value;
}
size_t taint_intro__get_packed_size
                     (const TaintIntro *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t taint_intro__pack
                     (const TaintIntro *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t taint_intro__pack_to_buffer
                     (const TaintIntro *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaintIntro *
       taint_intro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaintIntro *)
     protobuf_c_message_unpack (&taint_intro__descriptor,
                                allocator, len, data);
}
void   taint_intro__free_unpacked
                     (TaintIntro *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &taint_intro__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modload_frame__init
                     (ModloadFrame         *message)
{
  static ModloadFrame init_value = MODLOAD_FRAME__INIT;
  *message = init_value;
}
size_t modload_frame__get_packed_size
                     (const ModloadFrame *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &modload_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modload_frame__pack
                     (const ModloadFrame *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &modload_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modload_frame__pack_to_buffer
                     (const ModloadFrame *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &modload_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModloadFrame *
       modload_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModloadFrame *)
     protobuf_c_message_unpack (&modload_frame__descriptor,
                                allocator, len, data);
}
void   modload_frame__free_unpacked
                     (ModloadFrame *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &modload_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   key_frame__init
                     (KeyFrame         *message)
{
  static KeyFrame init_value = KEY_FRAME__INIT;
  *message = init_value;
}
size_t key_frame__get_packed_size
                     (const KeyFrame *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &key_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t key_frame__pack
                     (const KeyFrame *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &key_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t key_frame__pack_to_buffer
                     (const KeyFrame *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &key_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KeyFrame *
       key_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KeyFrame *)
     protobuf_c_message_unpack (&key_frame__descriptor,
                                allocator, len, data);
}
void   key_frame__free_unpacked
                     (KeyFrame *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &key_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tagged_value_lists__init
                     (TaggedValueLists         *message)
{
  static TaggedValueLists init_value = TAGGED_VALUE_LISTS__INIT;
  *message = init_value;
}
size_t tagged_value_lists__get_packed_size
                     (const TaggedValueLists *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_lists__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tagged_value_lists__pack
                     (const TaggedValueLists *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_lists__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tagged_value_lists__pack_to_buffer
                     (const TaggedValueLists *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_lists__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaggedValueLists *
       tagged_value_lists__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaggedValueLists *)
     protobuf_c_message_unpack (&tagged_value_lists__descriptor,
                                allocator, len, data);
}
void   tagged_value_lists__free_unpacked
                     (TaggedValueLists *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_lists__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tagged_value_list__init
                     (TaggedValueList         *message)
{
  static TaggedValueList init_value = TAGGED_VALUE_LIST__INIT;
  *message = init_value;
}
size_t tagged_value_list__get_packed_size
                     (const TaggedValueList *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tagged_value_list__pack
                     (const TaggedValueList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tagged_value_list__pack_to_buffer
                     (const TaggedValueList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaggedValueList *
       tagged_value_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaggedValueList *)
     protobuf_c_message_unpack (&tagged_value_list__descriptor,
                                allocator, len, data);
}
void   tagged_value_list__free_unpacked
                     (TaggedValueList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &tagged_value_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value_source_tag__init
                     (ValueSourceTag         *message)
{
  static ValueSourceTag init_value = VALUE_SOURCE_TAG__INIT;
  *message = init_value;
}
size_t value_source_tag__get_packed_size
                     (const ValueSourceTag *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_source_tag__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value_source_tag__pack
                     (const ValueSourceTag *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_source_tag__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value_source_tag__pack_to_buffer
                     (const ValueSourceTag *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_source_tag__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ValueSourceTag *
       value_source_tag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ValueSourceTag *)
     protobuf_c_message_unpack (&value_source_tag__descriptor,
                                allocator, len, data);
}
void   value_source_tag__free_unpacked
                     (ValueSourceTag *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_source_tag__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value_list__init
                     (ValueList         *message)
{
  static ValueList init_value = VALUE_LIST__INIT;
  *message = init_value;
}
size_t value_list__get_packed_size
                     (const ValueList *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value_list__pack
                     (const ValueList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value_list__pack_to_buffer
                     (const ValueList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ValueList *
       value_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ValueList *)
     protobuf_c_message_unpack (&value_list__descriptor,
                                allocator, len, data);
}
void   value_list__free_unpacked
                     (ValueList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value_info__init
                     (ValueInfo         *message)
{
  static ValueInfo init_value = VALUE_INFO__INIT;
  *message = init_value;
}
size_t value_info__get_packed_size
                     (const ValueInfo *message)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value_info__pack
                     (const ValueInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value_info__pack_to_buffer
                     (const ValueInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ValueInfo *
       value_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ValueInfo *)
     protobuf_c_message_unpack (&value_info__descriptor,
                                allocator, len, data);
}
void   value_info__free_unpacked
                     (ValueInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->__base.descriptor == &value_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor frame__field_descriptors[6] =
{
  {
    "std_frame",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Frame, std_frame),
    &std_frame__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "syscall_frame",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Frame, syscall_frame),
    &syscall_frame__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exception_frame",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Frame, exception_frame),
    &exception_frame__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_intro_frame",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Frame, taint_intro_frame),
    &taint_intro_frame__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modload_frame",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Frame, modload_frame),
    &modload_frame__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_frame",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Frame, key_frame),
    &key_frame__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned frame__field_indices_by_name[] = {
  2,   /* field[2] = exception_frame */
  5,   /* field[5] = key_frame */
  4,   /* field[4] = modload_frame */
  0,   /* field[0] = std_frame */
  1,   /* field[1] = syscall_frame */
  3,   /* field[3] = taint_intro_frame */
};
static const ProtobufCIntRange frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "frame",
  "Frame",
  "Frame",
  "",
  sizeof(Frame),
  6,
  frame__field_descriptors,
  frame__field_indices_by_name,
  1,  frame__number_ranges,
  (ProtobufCMessageInit) frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor operand_value_list__field_descriptors[1] =
{
  {
    "elem",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(OperandValueList, n_elem),
    PROTOBUF_C_OFFSETOF(OperandValueList, elem),
    &operand_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned operand_value_list__field_indices_by_name[] = {
  0,   /* field[0] = elem */
};
static const ProtobufCIntRange operand_value_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor operand_value_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "operand_value_list",
  "OperandValueList",
  "OperandValueList",
  "",
  sizeof(OperandValueList),
  1,
  operand_value_list__field_descriptors,
  operand_value_list__field_indices_by_name,
  1,  operand_value_list__number_ranges,
  (ProtobufCMessageInit) operand_value_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor operand_info__field_descriptors[5] =
{
  {
    "operand_info_specific",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandInfo, operand_info_specific),
    &operand_info_specific__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bit_length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandInfo, bit_length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operand_usage",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandInfo, operand_usage),
    &operand_usage__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_info",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandInfo, taint_info),
    &taint_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandInfo, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned operand_info__field_indices_by_name[] = {
  1,   /* field[1] = bit_length */
  0,   /* field[0] = operand_info_specific */
  2,   /* field[2] = operand_usage */
  3,   /* field[3] = taint_info */
  4,   /* field[4] = value */
};
static const ProtobufCIntRange operand_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor operand_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "operand_info",
  "OperandInfo",
  "OperandInfo",
  "",
  sizeof(OperandInfo),
  5,
  operand_info__field_descriptors,
  operand_info__field_indices_by_name,
  1,  operand_info__number_ranges,
  (ProtobufCMessageInit) operand_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor operand_info_specific__field_descriptors[2] =
{
  {
    "mem_operand",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandInfoSpecific, mem_operand),
    &mem_operand__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reg_operand",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandInfoSpecific, reg_operand),
    &reg_operand__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned operand_info_specific__field_indices_by_name[] = {
  0,   /* field[0] = mem_operand */
  1,   /* field[1] = reg_operand */
};
static const ProtobufCIntRange operand_info_specific__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor operand_info_specific__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "operand_info_specific",
  "OperandInfoSpecific",
  "OperandInfoSpecific",
  "",
  sizeof(OperandInfoSpecific),
  2,
  operand_info_specific__field_descriptors,
  operand_info_specific__field_indices_by_name,
  1,  operand_info_specific__number_ranges,
  (ProtobufCMessageInit) operand_info_specific__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reg_operand__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RegOperand, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reg_operand__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange reg_operand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor reg_operand__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "reg_operand",
  "RegOperand",
  "RegOperand",
  "",
  sizeof(RegOperand),
  1,
  reg_operand__field_descriptors,
  reg_operand__field_indices_by_name,
  1,  reg_operand__number_ranges,
  (ProtobufCMessageInit) reg_operand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mem_operand__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MemOperand, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mem_operand__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange mem_operand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mem_operand__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mem_operand",
  "MemOperand",
  "MemOperand",
  "",
  sizeof(MemOperand),
  1,
  mem_operand__field_descriptors,
  mem_operand__field_indices_by_name,
  1,  mem_operand__number_ranges,
  (ProtobufCMessageInit) mem_operand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor operand_usage__field_descriptors[4] =
{
  {
    "read",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandUsage, read),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "written",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandUsage, written),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandUsage, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperandUsage, base),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned operand_usage__field_indices_by_name[] = {
  3,   /* field[3] = base */
  2,   /* field[2] = index */
  0,   /* field[0] = read */
  1,   /* field[1] = written */
};
static const ProtobufCIntRange operand_usage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor operand_usage__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "operand_usage",
  "OperandUsage",
  "OperandUsage",
  "",
  sizeof(OperandUsage),
  4,
  operand_usage__field_descriptors,
  operand_usage__field_indices_by_name,
  1,  operand_usage__number_ranges,
  (ProtobufCMessageInit) operand_usage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor taint_info__field_descriptors[3] =
{
  {
    "no_taint",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(TaintInfo, has_no_taint),
    PROTOBUF_C_OFFSETOF(TaintInfo, no_taint),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(TaintInfo, has_taint_id),
    PROTOBUF_C_OFFSETOF(TaintInfo, taint_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_multiple",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(TaintInfo, has_taint_multiple),
    PROTOBUF_C_OFFSETOF(TaintInfo, taint_multiple),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned taint_info__field_indices_by_name[] = {
  0,   /* field[0] = no_taint */
  1,   /* field[1] = taint_id */
  2,   /* field[2] = taint_multiple */
};
static const ProtobufCIntRange taint_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor taint_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "taint_info",
  "TaintInfo",
  "TaintInfo",
  "",
  sizeof(TaintInfo),
  3,
  taint_info__field_descriptors,
  taint_info__field_indices_by_name,
  1,  taint_info__number_ranges,
  (ProtobufCMessageInit) taint_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor std_frame__field_descriptors[5] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StdFrame, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StdFrame, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rawbytes",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StdFrame, rawbytes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operand_pre_list",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StdFrame, operand_pre_list),
    &operand_value_list__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operand_post_list",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StdFrame, operand_post_list),
    &operand_value_list__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned std_frame__field_indices_by_name[] = {
  0,   /* field[0] = address */
  4,   /* field[4] = operand_post_list */
  3,   /* field[3] = operand_pre_list */
  2,   /* field[2] = rawbytes */
  1,   /* field[1] = thread_id */
};
static const ProtobufCIntRange std_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor std_frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "std_frame",
  "StdFrame",
  "StdFrame",
  "",
  sizeof(StdFrame),
  5,
  std_frame__field_descriptors,
  std_frame__field_indices_by_name,
  1,  std_frame__number_ranges,
  (ProtobufCMessageInit) std_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor syscall_frame__field_descriptors[4] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyscallFrame, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyscallFrame, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyscallFrame, number),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "argument_list",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyscallFrame, argument_list),
    &argument_list__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned syscall_frame__field_indices_by_name[] = {
  0,   /* field[0] = address */
  3,   /* field[3] = argument_list */
  2,   /* field[2] = number */
  1,   /* field[1] = thread_id */
};
static const ProtobufCIntRange syscall_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor syscall_frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "syscall_frame",
  "SyscallFrame",
  "SyscallFrame",
  "",
  sizeof(SyscallFrame),
  4,
  syscall_frame__field_descriptors,
  syscall_frame__field_indices_by_name,
  1,  syscall_frame__number_ranges,
  (ProtobufCMessageInit) syscall_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor argument_list__field_descriptors[1] =
{
  {
    "elem",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(ArgumentList, n_elem),
    PROTOBUF_C_OFFSETOF(ArgumentList, elem),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned argument_list__field_indices_by_name[] = {
  0,   /* field[0] = elem */
};
static const ProtobufCIntRange argument_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor argument_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "argument_list",
  "ArgumentList",
  "ArgumentList",
  "",
  sizeof(ArgumentList),
  1,
  argument_list__field_descriptors,
  argument_list__field_indices_by_name,
  1,  argument_list__number_ranges,
  (ProtobufCMessageInit) argument_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor exception_frame__field_descriptors[4] =
{
  {
    "exception_number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ExceptionFrame, exception_number),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ExceptionFrame, has_thread_id),
    PROTOBUF_C_OFFSETOF(ExceptionFrame, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "from_addr",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ExceptionFrame, has_from_addr),
    PROTOBUF_C_OFFSETOF(ExceptionFrame, from_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to_addr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ExceptionFrame, has_to_addr),
    PROTOBUF_C_OFFSETOF(ExceptionFrame, to_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned exception_frame__field_indices_by_name[] = {
  0,   /* field[0] = exception_number */
  2,   /* field[2] = from_addr */
  1,   /* field[1] = thread_id */
  3,   /* field[3] = to_addr */
};
static const ProtobufCIntRange exception_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor exception_frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "exception_frame",
  "ExceptionFrame",
  "ExceptionFrame",
  "",
  sizeof(ExceptionFrame),
  4,
  exception_frame__field_descriptors,
  exception_frame__field_indices_by_name,
  1,  exception_frame__number_ranges,
  (ProtobufCMessageInit) exception_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor taint_intro_frame__field_descriptors[1] =
{
  {
    "taint_intro_list",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaintIntroFrame, taint_intro_list),
    &taint_intro_list__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned taint_intro_frame__field_indices_by_name[] = {
  0,   /* field[0] = taint_intro_list */
};
static const ProtobufCIntRange taint_intro_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor taint_intro_frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "taint_intro_frame",
  "TaintIntroFrame",
  "TaintIntroFrame",
  "",
  sizeof(TaintIntroFrame),
  1,
  taint_intro_frame__field_descriptors,
  taint_intro_frame__field_indices_by_name,
  1,  taint_intro_frame__number_ranges,
  (ProtobufCMessageInit) taint_intro_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor taint_intro_list__field_descriptors[1] =
{
  {
    "elem",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TaintIntroList, n_elem),
    PROTOBUF_C_OFFSETOF(TaintIntroList, elem),
    &taint_intro__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned taint_intro_list__field_indices_by_name[] = {
  0,   /* field[0] = elem */
};
static const ProtobufCIntRange taint_intro_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor taint_intro_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "taint_intro_list",
  "TaintIntroList",
  "TaintIntroList",
  "",
  sizeof(TaintIntroList),
  1,
  taint_intro_list__field_descriptors,
  taint_intro_list__field_indices_by_name,
  1,  taint_intro_list__number_ranges,
  (ProtobufCMessageInit) taint_intro_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor taint_intro__field_descriptors[5] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaintIntro, addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaintIntro, taint_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(TaintIntro, has_value),
    PROTOBUF_C_OFFSETOF(TaintIntro, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaintIntro, source_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(TaintIntro, has_offset),
    PROTOBUF_C_OFFSETOF(TaintIntro, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned taint_intro__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  4,   /* field[4] = offset */
  3,   /* field[3] = source_name */
  1,   /* field[1] = taint_id */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange taint_intro__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor taint_intro__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "taint_intro",
  "TaintIntro",
  "TaintIntro",
  "",
  sizeof(TaintIntro),
  5,
  taint_intro__field_descriptors,
  taint_intro__field_indices_by_name,
  1,  taint_intro__number_ranges,
  (ProtobufCMessageInit) taint_intro__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modload_frame__field_descriptors[3] =
{
  {
    "module_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ModloadFrame, module_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "low_address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ModloadFrame, low_address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "high_address",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ModloadFrame, high_address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modload_frame__field_indices_by_name[] = {
  2,   /* field[2] = high_address */
  1,   /* field[1] = low_address */
  0,   /* field[0] = module_name */
};
static const ProtobufCIntRange modload_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor modload_frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "modload_frame",
  "ModloadFrame",
  "ModloadFrame",
  "",
  sizeof(ModloadFrame),
  3,
  modload_frame__field_descriptors,
  modload_frame__field_indices_by_name,
  1,  modload_frame__number_ranges,
  (ProtobufCMessageInit) modload_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor key_frame__field_descriptors[1] =
{
  {
    "tagged_value_lists",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(KeyFrame, tagged_value_lists),
    &tagged_value_lists__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned key_frame__field_indices_by_name[] = {
  0,   /* field[0] = tagged_value_lists */
};
static const ProtobufCIntRange key_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor key_frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "key_frame",
  "KeyFrame",
  "KeyFrame",
  "",
  sizeof(KeyFrame),
  1,
  key_frame__field_descriptors,
  key_frame__field_indices_by_name,
  1,  key_frame__number_ranges,
  (ProtobufCMessageInit) key_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tagged_value_lists__field_descriptors[1] =
{
  {
    "elem",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TaggedValueLists, n_elem),
    PROTOBUF_C_OFFSETOF(TaggedValueLists, elem),
    &tagged_value_list__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tagged_value_lists__field_indices_by_name[] = {
  0,   /* field[0] = elem */
};
static const ProtobufCIntRange tagged_value_lists__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tagged_value_lists__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "tagged_value_lists",
  "TaggedValueLists",
  "TaggedValueLists",
  "",
  sizeof(TaggedValueLists),
  1,
  tagged_value_lists__field_descriptors,
  tagged_value_lists__field_indices_by_name,
  1,  tagged_value_lists__number_ranges,
  (ProtobufCMessageInit) tagged_value_lists__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tagged_value_list__field_descriptors[2] =
{
  {
    "value_source_tag",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaggedValueList, value_source_tag),
    &value_source_tag__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_list",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaggedValueList, value_list),
    &value_list__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tagged_value_list__field_indices_by_name[] = {
  1,   /* field[1] = value_list */
  0,   /* field[0] = value_source_tag */
};
static const ProtobufCIntRange tagged_value_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tagged_value_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "tagged_value_list",
  "TaggedValueList",
  "TaggedValueList",
  "",
  sizeof(TaggedValueList),
  2,
  tagged_value_list__field_descriptors,
  tagged_value_list__field_indices_by_name,
  1,  tagged_value_list__number_ranges,
  (ProtobufCMessageInit) tagged_value_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value_source_tag__field_descriptors[2] =
{
  {
    "no_thread_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ValueSourceTag, has_no_thread_id),
    PROTOBUF_C_OFFSETOF(ValueSourceTag, no_thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ValueSourceTag, has_thread_id),
    PROTOBUF_C_OFFSETOF(ValueSourceTag, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value_source_tag__field_indices_by_name[] = {
  0,   /* field[0] = no_thread_id */
  1,   /* field[1] = thread_id */
};
static const ProtobufCIntRange value_source_tag__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor value_source_tag__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "value_source_tag",
  "ValueSourceTag",
  "ValueSourceTag",
  "",
  sizeof(ValueSourceTag),
  2,
  value_source_tag__field_descriptors,
  value_source_tag__field_indices_by_name,
  1,  value_source_tag__number_ranges,
  (ProtobufCMessageInit) value_source_tag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value_list__field_descriptors[1] =
{
  {
    "elem",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(ValueList, n_elem),
    PROTOBUF_C_OFFSETOF(ValueList, elem),
    &value_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value_list__field_indices_by_name[] = {
  0,   /* field[0] = elem */
};
static const ProtobufCIntRange value_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor value_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "value_list",
  "ValueList",
  "ValueList",
  "",
  sizeof(ValueList),
  1,
  value_list__field_descriptors,
  value_list__field_indices_by_name,
  1,  value_list__number_ranges,
  (ProtobufCMessageInit) value_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value_info__field_descriptors[4] =
{
  {
    "operand_info_specific",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ValueInfo, operand_info_specific),
    &operand_info_specific__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bit_length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ValueInfo, bit_length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taint_info",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ValueInfo, taint_info),
    &taint_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ValueInfo, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value_info__field_indices_by_name[] = {
  1,   /* field[1] = bit_length */
  0,   /* field[0] = operand_info_specific */
  2,   /* field[2] = taint_info */
  3,   /* field[3] = value */
};
static const ProtobufCIntRange value_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor value_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "value_info",
  "ValueInfo",
  "ValueInfo",
  "",
  sizeof(ValueInfo),
  4,
  value_info__field_descriptors,
  value_info__field_indices_by_name,
  1,  value_info__number_ranges,
  (ProtobufCMessageInit) value_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
